server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
        #GitHub上面的git仓库名字
          uri: https://github.com/zhuxianshengs/springcloud-config.git
          #uri: git@github.com:zhuxianshengs/springcloud-config.git
        ####搜索目录
          search-paths:
            - springcloud-config
      ####读取分支
      label: master

rabbitmq:
  host: loclahost
  port: 5672
  username: guest
  password: guest

eureka:
  client:
    service-url:
     defaultZone: http://localhost:7001/eureka


#rabbitmq相关配置，暴露bus刷新配置的端点
managment:
  endpiont:
    web:
      exposure:
        incloud: 'bus-refresh'